export const PRODUCT_ACTION_TYPES = {
  SET_PRODUCT_FAV: "product/SET_PRODUCT_FAV",
  SET_PRODUCT_ADD: "product/SET_PRODUCT_ADD",
  SET_PRODUCT_DEL: "product/SET_PRODUCT_DEL",
  SET_PRODUCT_LOAD: "product/SET_PRODUCT_LOAD",
};
